DATABASE_USER: "ching"
DATABASE_PASSWORD: "978775!Rtj01"
DATABASE_HOST: "aws-bot-world-mysql.c6ecc5e9b7no.ap-southeast-1.rds.amazonaws.com"
DATABASE_NAME: "Arietes_Care"
PRODUCT_INFO_TABLE_NAME: "product_info"
