# Use an official Nginx image as the base image
# FROM nginx:alpine
FROM soulteary/prebuilt-nginx-modules:set-misc-1.21.0

# Expose port 80 for the Nginx server
EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]