# Use an official Nginx image as the base image
FROM nginx:alpine

# COPY /usr/lib/nginx/modules/ngx_http_set_misc_module.so /usr/lib/nginx/modules/ngx_http_set_misc_module.so

# Expose port 80 for the Nginx server
EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]