# Use an official Nginx image as the base image
# FROM nginx:alpine
FROM soulteary/prebuilt-nginx-modules:ngx-1.21.1-set-misc-master

# Expose port 80 for the Nginx server
EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]